In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv(r'C:\Users\Lenovo\Downloads\swan\Swarm_Behaviour.csv')

In [2]:
data

x1      y1  xVel1  yVel1   xA1   yA1  xS1  yS1   xC1   yC1  ...  \
0       562.05   -0.62 -10.70  -4.33  0.00  0.00  0.0  0.0  0.00  0.00  ...   
1       175.66  -57.09   2.31  -2.67  0.00  0.00  0.0  0.0  0.00  0.00  ...   
2       200.16 -320.07   4.01  -6.37  0.00  0.00  0.0  0.0  0.18 -0.26  ...   
3       316.99 -906.84   0.85   9.17 -0.17  1.03  0.0  0.0  0.00  0.00  ...   
4      1277.68  908.54  -2.02   8.23 -1.00  1.00  0.0  0.0  0.00  0.00  ...   
...        ...     ...    ...    ...   ...   ...  ...  ...   ...   ...  ...   
23304  -225.85  128.99  12.19  -7.56 -1.00  0.00  0.0  0.0  0.00  0.00  ...   
23305 -1352.02 -233.03  -0.86  -4.37 -0.07 -0.55  0.0  0.0  0.28  0.02  ...   
23306 -1360.61 -778.11  -2.89  -1.17  0.00  0.00  0.0  0.0  0.00  0.00  ...   
23307   987.11  615.69  -5.61  -2.92 -1.00 -1.00  0.0  0.0  0.00  0.00  ...   
23308   938.12 -924.87  11.18   2.85  0.10 -0.02  0.0  0.0  0.06  0.31  ...   

       yVel200  xA200  yA200  xS200  yS200  xC200  yC200  nAC200  nS200  \
0       -15.15   0.00   0.00   0.00   0.00   0.00   0.00      28      0   
1        -3.48   0.00   0.00   0.00   0.00   0.00   0.00       4      0   
2        -9.38   0.00   0.00   0.00   0.00  -0.11  -0.30      15      1   
3        10.39  -0.26   1.01   0.00   0.00   0.00   0.00      16      0   
4        13.91  -1.00   0.00   3.21  15.67   0.00   0.00      12      0   
...        ...    ...    ...    ...    ...    ...    ...     ...    ...   
23304    -5.06  -1.00  -1.00  -3.99   0.21   0.00   0.00      17      1   
23305   -12.41  -0.15  -0.70   0.00   0.00   0.02   0.07      69      1   
23306   -14.78   0.00   0.00   0.00   0.00   0.00   0.00      20      1   
23307     9.78  -1.00  -1.00   0.00   0.00   0.00   0.00      29      0   
23308    -2.90  -0.13  -0.29   1.31   0.38   0.00   0.00       2      1   

       Swarm_Behaviour  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0  
...                ...  
23304              0.0  
23305              0.0  
23306              0.0  
23307              0.0  
23308              0.0  

[23309 rows x 2401 columns]

In [3]:
data["Swarm_Behaviour"].value_counts()

0.0    15355
1.0     7954
Name: Swarm_Behaviour, dtype: int64

In [4]:
data.notnull().sum()

x1                 23309
y1                 23309
xVel1              23309
yVel1              23309
xA1                23309
                   ...  
xC200              23309
yC200              23309
nAC200             23309
nS200              23309
Swarm_Behaviour    23309
Length: 2401, dtype: int64

In [5]:
import warnings 
warnings.filterwarnings("ignore")

In [6]:
d_1=data[data["Swarm_Behaviour"]==1]
d_0=data[data["Swarm_Behaviour"]==0]
m=min(data["Swarm_Behaviour"].value_counts())
d_1=d_1[:m]

In [7]:
data=pd.concat([d_0,d_1]).sample(frac=1)

# Logistic Regression

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [9]:
x=data.drop("Swarm_Behaviour",axis=1)
y=data["Swarm_Behaviour"]

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)

In [11]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [12]:
y_pred_l=model.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
confusion_matrix(y_test,y_pred_l)

array([[4283,  329],
       [ 353, 2028]], dtype=int64)

In [14]:
print(classification_report(y_test, y_pred_l))

              precision    recall  f1-score   support

         0.0       0.92      0.93      0.93      4612
         1.0       0.86      0.85      0.86      2381

    accuracy                           0.90      6993
   macro avg       0.89      0.89      0.89      6993
weighted avg       0.90      0.90      0.90      6993



# KNN

In [15]:
 from sklearn.neighbors import KNeighborsClassifier

In [16]:
knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  

In [17]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [18]:
y_pred_knn=knn.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
confusion_matrix(y_test,y_pred_knn)

array([[4223,  389],
       [ 352, 2029]], dtype=int64)

In [20]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

         0.0       0.92      0.92      0.92      4612
         1.0       0.84      0.85      0.85      2381

    accuracy                           0.89      6993
   macro avg       0.88      0.88      0.88      6993
weighted avg       0.89      0.89      0.89      6993



# Naive Bayes

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [23]:
y_pred_nb=classifier.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
confusion_matrix(y_test,y_pred_nb)

array([[ 818, 3794],
       [ 100, 2281]], dtype=int64)

In [25]:
print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

         0.0       0.89      0.18      0.30      4612
         1.0       0.38      0.96      0.54      2381

    accuracy                           0.44      6993
   macro avg       0.63      0.57      0.42      6993
weighted avg       0.72      0.44      0.38      6993



# Decision Tree entropy

In [26]:
from sklearn.tree import DecisionTreeClassifier  

In [27]:
tree= DecisionTreeClassifier(criterion='entropy', random_state=0)  

In [28]:
tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [29]:
y_pred_dt=tree.predict(x_test)

In [30]:
confusion_matrix(y_test,y_pred_dt)

array([[4208,  404],
       [ 469, 1912]], dtype=int64)

In [31]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

         0.0       0.90      0.91      0.91      4612
         1.0       0.83      0.80      0.81      2381

    accuracy                           0.88      6993
   macro avg       0.86      0.86      0.86      6993
weighted avg       0.87      0.88      0.87      6993



# Decision Tree gini

In [32]:
tree_g= DecisionTreeClassifier(criterion='gini', random_state=0) 
tree_g.fit(x_train,y_train)

y_pred_dt_g=tree_g.predict(x_test)

In [33]:
confusion_matrix(y_test,y_pred_dt_g)

array([[4173,  439],
       [ 459, 1922]], dtype=int64)

In [34]:
print(classification_report(y_test, y_pred_dt_g))

              precision    recall  f1-score   support

         0.0       0.90      0.90      0.90      4612
         1.0       0.81      0.81      0.81      2381

    accuracy                           0.87      6993
   macro avg       0.86      0.86      0.86      6993
weighted avg       0.87      0.87      0.87      6993



# Comparing accuracy

In [35]:
from sklearn.model_selection import cross_val_score,KFold

kf = KFold(n_splits=10)

In [36]:
LR=cross_val_score(model,x,y,cv=kf,scoring="f1").mean()

In [37]:
KNN=cross_val_score(knn,x,y,cv=kf,scoring="f1").mean()

In [38]:
NB=cross_val_score(classifier,x,y,cv=kf,scoring="f1").mean()

In [39]:
DT_e=cross_val_score(tree,x,y,cv=kf,scoring="f1").mean()

KeyboardInterrupt: 

In [ ]:
DT_g=cross_val_score(tree_g,x,y,cv=kf,scoring="f1").mean()

In [ ]:
LR

In [ ]:
KNN

In [ ]:
NB

In [ ]:
DT_e

In [ ]:
DT_g